<?php
$messages = array();
$messages['lastlogin'] = 'Ostatnia otwarta sesja: $date z adresu IP $from $geo.';
$messages['noinfo']    = 'Brak dostępnych informacji.';
$messages['timeout']   = 'Pokaz informacje o ostaniej sesji';
$labels = array();
$labels['section_title'] = 'Ostatnie logowanie';
$labels['info'] = 'Informacje';
$labels['conf'] = 'Ustawienia';
$labels['fornseconds'] = 'przez $n sekund';
$labels['recentactivity'] = 'Ostatnia aktywność:';
$labels['ip'] = 'adres IP';
$labels['hostname'] = 'Nazwa';
$labels['timestamp'] = 'Data/Czas';
$labels['today'] = 'dziś';
$labels['yesterday'] = 'wczoraj';
$labels['geoip_license'] = 'Dane geograficzne przedstawione w tym miejscu są dostarczane i oparte na darmowej bazie GeoLite2 stworzonej przez MaxMind, dostępnej pod adresem <a href="http://www.maxmind.com">http://www.maxmind.com</a>.';
